<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jurnal_kegiatan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get jurnal_kegiatan by id_jurnal
     */
    function get_jurnal_kegiatan($id_jurnal)
    {
        return $this->db->get_where('jurnal_kegiatan',array('id_jurnal'=>$id_jurnal))->row_array();
    }
    
    /*
     * Get all jurnal_kegiatan count
     */
    function get_all_jurnal_kegiatan_count()
    {
        $this->db->from('jurnal_kegiatan');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all jurnal_kegiatan
     */
    function get_all_jurnal_kegiatan($params = array())
    {
        $this->db->order_by('id_jurnal', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('jurnal_kegiatan')->result_array();
    }
        
    /*
     * function to add new jurnal_kegiatan
     */
    function add_jurnal_kegiatan($params)
    {
        $this->db->insert('jurnal_kegiatan',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update jurnal_kegiatan
     */
    function update_jurnal_kegiatan($id_jurnal,$params)
    {
        $this->db->where('id_jurnal',$id_jurnal);
        return $this->db->update('jurnal_kegiatan',$params);
    }
    
    /*
     * function to delete jurnal_kegiatan
     */
    function delete_jurnal_kegiatan($id_jurnal)
    {
        return $this->db->delete('jurnal_kegiatan',array('id_jurnal'=>$id_jurnal));
    }
}
