<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Komoditas_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get komoditas by id_komoditas
     */
    function get_komoditas($id_komoditas)
    {
        return $this->db->get_where('komoditas',array('id_komoditas'=>$id_komoditas))->row_array();
    }
    
    /*
     * Get all komoditas count
     */
    function get_all_komoditas_count()
    {
        $this->db->from('komoditas');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all komoditas
     */
    function get_all_komoditas($params = array())
    {
        $this->db->order_by('id_komoditas', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('komoditas')->result_array();
    }
        
    /*
     * function to add new komoditas
     */
    function add_komoditas($params)
    {
        $this->db->insert('komoditas',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update komoditas
     */
    function update_komoditas($id_komoditas,$params)
    {
        $this->db->where('id_komoditas',$id_komoditas);
        return $this->db->update('komoditas',$params);
    }
    
    /*
     * function to delete komoditas
     */
    function delete_komoditas($id_komoditas)
    {
        return $this->db->delete('komoditas',array('id_komoditas'=>$id_komoditas));
    }
}
