<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Panen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get panen by id_panen
     */
    function get_panen($id_panen)
    {
        return $this->db->get_where('panen',array('id_panen'=>$id_panen))->row_array();
    }
    
    /*
     * Get all panen count
     */
    function get_all_panen_count()
    {
        $this->db->from('panen');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all panen
     */
    function get_all_panen($params = array())
    {
        $this->db->order_by('id_panen', 'desc');
        $this->db->join('komoditas', 'komoditas.id_komoditas=panen.id_komoditas', 'left');
        $this->db->join('luasan', 'luasan.id_luasan=panen.id_luasan', 'left');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('panen')->result_array();
    }
        
    /*
     * function to add new panen
     */
    function add_panen($params)
    {
        $this->db->insert('panen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update panen
     */
    function update_panen($id_panen,$params)
    {
        $this->db->where('id_panen',$id_panen);
        return $this->db->update('panen',$params);
    }
    
    /*
     * function to delete panen
     */
    function delete_panen($id_panen)
    {
        return $this->db->delete('panen',array('id_panen'=>$id_panen));
    }
}
