<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Absen extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // $this->load->model('Jamaah_model');
    }

    /*
     * Listing of luasan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('absen/index?');
        $this->pagination->initialize($config);
        $data['_view'] = 'absen/index';
        $this->load->view('layouts/main', $data);
    }

    public function messageAlert($type, $title)
    {
        $messageAlert = "const Toast = Swal.mixin({
			toast: true,
			position: 'top-end',
			showConfirmButton: false,
			timer: 3000
		});
		Toast.fire({
			type: '" . $type . "',
			title: '" . $title . "'
		});";
        return $messageAlert;
    }
    function cek_id()
    {
        $result_code = $this->input->post('uuid');
        $tgl = date('Y-m-d');
        $jam_msk = date('h:i:s');
        $jam_klr = date('h:i:s');
        $get_jamaah = $this->Jamaah_model->get_jamaah_by_uuid($result_code);
        if ($get_jamaah != null) {
            $params = array(
                'kehadiran' => 'Hadir',
            );
            $this->Jamaah_model->update_scan($result_code, $params);
            $this->session->set_flashdata('jk', $get_jamaah['jenis_kelamin']);
            $this->session->set_flashdata('nama_jamaah', $get_jamaah['nama_jamaah']);
            redirect('scan/index');
        } else {
            $this->session->set_flashdata('jk', '');
            $this->session->set_flashdata('error', 'Jamaah Tidak Ditemukan');
            redirect('scan/index');
        }
    }
    function remove($id_kehadiran)
    {
        $kehadiran = $this->Scan_model->get_kehadiran($id_kehadiran);

        // check if the kehadiran exists before trying to delete it
        if (isset($kehadiran['id_kehadiran'])) {
            $this->Scan_model->delete_kehadiran($id_kehadiran);
            redirect('scan/index');
        } else
            show_error('The kehadiran you are trying to delete does not exist.');
    }
}
