<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Jurnal_kegiatan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Jurnal_kegiatan_model');
    } 

    /*
     * Listing of jurnal_kegiatan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('jurnal_kegiatan/index?');
        $config['total_rows'] = $this->Jurnal_kegiatan_model->get_all_jurnal_kegiatan_count();
        $this->pagination->initialize($config);

        $data['jurnal_kegiatan'] = $this->Jurnal_kegiatan_model->get_all_jurnal_kegiatan($params);
        
        $data['_view'] = 'jurnal_kegiatan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new jurnal_kegiatan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama_kegiatan' => $this->input->post('nama_kegiatan'),
				'uraian' => $this->input->post('uraian'),
				'tanggal_kegiatan' => $this->input->post('tanggal_kegiatan'),
            );
            
            $jurnal_kegiatan_id = $this->Jurnal_kegiatan_model->add_jurnal_kegiatan($params);
            redirect('jurnal_kegiatan/index');
        }
        else
        {            
            $data['_view'] = 'jurnal_kegiatan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a jurnal_kegiatan
     */
    function edit($id_jurnal)
    {   
        // check if the jurnal_kegiatan exists before trying to edit it
        $data['jurnal_kegiatan'] = $this->Jurnal_kegiatan_model->get_jurnal_kegiatan($id_jurnal);
        
        if(isset($data['jurnal_kegiatan']['id_jurnal']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama_kegiatan' => $this->input->post('nama_kegiatan'),
					'uraian' => $this->input->post('uraian'),
					'tanggal_kegiatan' => $this->input->post('tanggal_kegiatan'),
                );

                $this->Jurnal_kegiatan_model->update_jurnal_kegiatan($id_jurnal,$params);            
                redirect('jurnal_kegiatan/index');
            }
            else
            {
                $data['_view'] = 'jurnal_kegiatan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The jurnal_kegiatan you are trying to edit does not exist.');
    } 

    /*
     * Deleting jurnal_kegiatan
     */
    function remove($id_jurnal)
    {
        $jurnal_kegiatan = $this->Jurnal_kegiatan_model->get_jurnal_kegiatan($id_jurnal);

        // check if the jurnal_kegiatan exists before trying to delete it
        if(isset($jurnal_kegiatan['id_jurnal']))
        {
            $this->Jurnal_kegiatan_model->delete_jurnal_kegiatan($id_jurnal);
            redirect('jurnal_kegiatan/index');
        }
        else
            show_error('The jurnal_kegiatan you are trying to delete does not exist.');
    }
    
}
