<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Komoditas extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Komoditas_model');
    } 

    /*
     * Listing of komoditas
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('komoditas/index?');
        $config['total_rows'] = $this->Komoditas_model->get_all_komoditas_count();
        $this->pagination->initialize($config);

        $data['komoditas'] = $this->Komoditas_model->get_all_komoditas($params);
        
        $data['_view'] = 'komoditas/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new komoditas
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'nama_komoditas' => $this->input->post('nama_komoditas'),
            );
            
            $komoditas_id = $this->Komoditas_model->add_komoditas($params);
            redirect('komoditas/index');
        }
        else
        {            
            $data['_view'] = 'komoditas/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a komoditas
     */
    function edit($id_komoditas)
    {   
        // check if the komoditas exists before trying to edit it
        $data['komoditas'] = $this->Komoditas_model->get_komoditas($id_komoditas);
        
        if(isset($data['komoditas']['id_komoditas']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'nama_komoditas' => $this->input->post('nama_komoditas'),
                );

                $this->Komoditas_model->update_komoditas($id_komoditas,$params);            
                redirect('komoditas/index');
            }
            else
            {
                $data['_view'] = 'komoditas/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The komoditas you are trying to edit does not exist.');
    } 

    /*
     * Deleting komoditas
     */
    function remove($id_komoditas)
    {
        $komoditas = $this->Komoditas_model->get_komoditas($id_komoditas);

        // check if the komoditas exists before trying to delete it
        if(isset($komoditas['id_komoditas']))
        {
            $this->Komoditas_model->delete_komoditas($id_komoditas);
            redirect('komoditas/index');
        }
        else
            show_error('The komoditas you are trying to delete does not exist.');
    }
    
}
