<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Luasan extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Luasan_model');
    } 

    /*
     * Listing of luasan
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('luasan/index?');
        $config['total_rows'] = $this->Luasan_model->get_all_luasan_count();
        $this->pagination->initialize($config);

        $data['luasan'] = $this->Luasan_model->get_all_luasan($params);
        
        $data['_view'] = 'luasan/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new luasan
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'status' => $this->input->post('status'),
				'nama_luasan' => $this->input->post('nama_luasan'),
				'luas' => $this->input->post('luas'),
            );
            
            $luasan_id = $this->Luasan_model->add_luasan($params);
            redirect('luasan/index');
        }
        else
        {            
            $data['_view'] = 'luasan/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a luasan
     */
    function edit($id_luasan)
    {   
        // check if the luasan exists before trying to edit it
        $data['luasan'] = $this->Luasan_model->get_luasan($id_luasan);
        
        if(isset($data['luasan']['id_luasan']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'status' => $this->input->post('status'),
					'nama_luasan' => $this->input->post('nama_luasan'),
					'luas' => $this->input->post('luas'),
                );

                $this->Luasan_model->update_luasan($id_luasan,$params);            
                redirect('luasan/index');
            }
            else
            {
                $data['_view'] = 'luasan/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The luasan you are trying to edit does not exist.');
    } 

    /*
     * Deleting luasan
     */
    function remove($id_luasan)
    {
        $luasan = $this->Luasan_model->get_luasan($id_luasan);

        // check if the luasan exists before trying to delete it
        if(isset($luasan['id_luasan']))
        {
            $this->Luasan_model->delete_luasan($id_luasan);
            redirect('luasan/index');
        }
        else
            show_error('The luasan you are trying to delete does not exist.');
    }
    
}
