<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Panen extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Panen_model');
    } 

    /*
     * Listing of panen
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('panen/index?');
        $config['total_rows'] = $this->Panen_model->get_all_panen_count();
        $this->pagination->initialize($config);

        $data['panen'] = $this->Panen_model->get_all_panen($params);
        
        $data['_view'] = 'panen/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new panen
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'id_komoditas' => $this->input->post('id_komoditas'),
				'id_luasan' => $this->input->post('id_luasan'),
				'hasil_panen' => $this->input->post('hasil_panen'),
				'tanggal_panen' => $this->input->post('tanggal_panen'),
            );
            
            $panen_id = $this->Panen_model->add_panen($params);
            redirect('panen/index');
        }
        else
        {            
            $this->load->model('Komoditas_model');
            $data['komoditases'] = $this->Komoditas_model->get_all_komoditas();
            $this->load->model('Luasan_model');
            $data['luasanes'] = $this->Luasan_model->get_all_luasan();
            $data['_view'] = 'panen/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a panen
     */
    function edit($id_panen)
    {   
        // check if the panen exists before trying to edit it
        $data['panen'] = $this->Panen_model->get_panen($id_panen);
        
        if(isset($data['panen']['id_panen']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'id_komoditas' => $this->input->post('id_komoditas'),
					'id_luasan' => $this->input->post('id_luasan'),
					'hasil_panen' => $this->input->post('hasil_panen'),
					'tanggal_panen' => $this->input->post('tanggal_panen'),
                );

                $this->Panen_model->update_panen($id_panen,$params);            
                redirect('panen/index');
            }
            else
            {
                $data['_view'] = 'panen/edit';

                $this->load->model('Komoditas_model');
                $data['komoditases'] = $this->Komoditas_model->get_all_komoditas();
                $this->load->model('Luasan_model');
                $data['luasanes'] = $this->Luasan_model->get_all_luasan();

                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The panen you are trying to edit does not exist.');
    } 

    /*
     * Deleting panen
     */
    function remove($id_panen)
    {
        $panen = $this->Panen_model->get_panen($id_panen);

        // check if the panen exists before trying to delete it
        if(isset($panen['id_panen']))
        {
            $this->Panen_model->delete_panen($id_panen);
            redirect('panen/index');
        }
        else
            show_error('The panen you are trying to delete does not exist.');
    }
    
}
