<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Tanam extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tanam_model');
    }

    /*
     * Listing of tanam
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE;
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;

        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('tanam/index?');
        $config['total_rows'] = $this->Tanam_model->get_all_tanam_count();
        $this->pagination->initialize($config);

        $data['tanam'] = $this->Tanam_model->get_all_tanam($params);

        $data['_view'] = 'tanam/index';
        $this->load->view('layouts/main', $data);
    }

    /*
     * Adding a new tanam
     */
    function add()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $params = array(
                'id_komoditas' => $this->input->post('id_komoditas'),
                'id_luasan' => $this->input->post('id_luasan'),
                'tanggal_tanam' => $this->input->post('tanggal_tanam'),
            );

            $tanam_id = $this->Tanam_model->add_tanam($params);
            redirect('tanam/index');
        } else {
            $this->load->model('Komoditas_model');
            $data['komoditases'] = $this->Komoditas_model->get_all_komoditas();
            $this->load->model('Luasan_model');
            $data['luasanes'] = $this->Luasan_model->get_all_luasan();
            $data['_view'] = 'tanam/add';
            $this->load->view('layouts/main', $data);
        }
    }

    /*
     * Editing a tanam
     */
    function edit($id_tanam)
    {
        // check if the tanam exists before trying to edit it
        $data['tanam'] = $this->Tanam_model->get_tanam($id_tanam);
        
        if (isset($data['tanam']['id_tanam'])) {
            if (isset($_POST) && count($_POST) > 0) {
                $params = array(
                    'id_komoditas' => $this->input->post('id_komoditas'),
                    'id_luasan' => $this->input->post('id_luasan'),
                    'tanggal_tanam' => $this->input->post('tanggal_tanam'),
                );
                
                $this->Tanam_model->update_tanam($id_tanam, $params);
                redirect('tanam/index');
            } else {
                $data['_view'] = 'tanam/edit';
                
                $this->load->model('Komoditas_model');
                $data['komoditases'] = $this->Komoditas_model->get_all_komoditas();
                $this->load->model('Luasan_model');
                $data['luasanes'] = $this->Luasan_model->get_all_luasan();

                $this->load->view('layouts/main', $data);
            }
        } else
            show_error('The tanam you are trying to edit does not exist.');
    }

    /*
     * Deleting tanam
     */
    function remove($id_tanam)
    {
        $tanam = $this->Tanam_model->get_tanam($id_tanam);

        // check if the tanam exists before trying to delete it
        if (isset($tanam['id_tanam'])) {
            $this->Tanam_model->delete_tanam($id_tanam);
            redirect('tanam/index');
        } else
            show_error('The tanam you are trying to delete does not exist.');
    }
}
